spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/./capstone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

file.local-path : C:\Users\alsju\Desktop\capstone_folder\crop_image_test

logging:
  file:
    name: ./build/logs/app-local
    max-history: 1
    max-size: 10MB

