name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

# 본인이 설정한 값을 여기서 채워넣습니다.
# 리전, 버킷 이름, CodeDeploy 앱 이름, CodeDeploy 배포 그룹 이름
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: capstone-s3
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeploy-deployment-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (2) JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ignore yml 파일 추가
      - name: Copy prod secret
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
          PROD_SECRET_DIR: src/main/resources
          PROD_SECRET_DIR_FILE_NAME: application-prod.yml
        run: echo $PROD_SECRET | base64 --decode >> $PROD_SECRET_DIR/$PROD_SECRET_DIR_FILE_NAME

      - name: Copy security secret
        env:
          SECURITY_SECRET: ${{ secrets.SECURITY_SECRET }}
          SECURITY_SECRET_DIR: src/main/resources
          SECURITY_SECRET_DIR_FILE_NAME: application-security.yml
        run: echo $SECURITY_SECRET | base64 --decode >> $SECURITY_SECRET_DIR/$SECURITY_SECRET_DIR_FILE_NAME

      # Error Gradle Script ‘/Home/Runner/Work/*/Gradlew’ Is Not Executable 에러 해결
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # (3) Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean build -x test

      # (4) Docker build & push to DockerHub
      - name : Docker build & push to DockerHub
        run : |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:spring .
          docker push ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:spring

      # (5) Deploy to AWS EC2
      - name : Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f $(docker ps -qa)
            docker pull ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:spring
            docker pull ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:nginx8080
            docker-compose up -d
            docker rmi -f ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:spring
            docker rmi -f ${{ secrets.DOCKER_USERNAME }}/sejong-capstone:nginx8080